name: Pre-commit Hooks

on:
  schedule:
    - cron: "0 8 * * 1" # Monday 8am UTC
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-python: true
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
      - run: uv sync --dev --locked

      - name: Update pre-commit hooks
        run: uv run pre-commit autoupdate

      - name: Create PR if changed
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "ci: update pre-commit hooks"
          title: "CI: Update pre-commit hooks"
          branch: auto/pre-commit-update
          delete-branch: true
          body: |
            Automated pre-commit hook version update via `pre-commit autoupdate`.
